### ISSUE TITLE
Fill Empty Card Class Methods!

### ISSUE THREAD

**Issue by jagernet-ops** [python-42/fast-fish#2]
We currently have a ton of empty methods in our card classes. 

A couple to start with are as follows:
* In card collection
* Other currently empty methods

**Comment by jherrmann06** [comment]
I think we should split up this issue. I will implement the existing issues and you could implement the inCardCollection method. Make sure to add it to the abstract class then override it and implement in in the two extending classes. I will open a new issue for this.

**Comment by jherrmann06** [comment]
#8
